CRETE TABLE CHARACTER (
  CHARACTER_ID VARCHAR (36),
  NAME VARCHAR (128),
  HOME_WORLD VARCHAR (128),
  GENDER VARCHAR (32),
  HEIGHT int,
  MASS int,
  HAIR_COLOR VARCHAR (64),
  SKIN_COLOR VARCHAR (64),
  PRIMARY KEY (CHARACTER_ID)
);
